# recipe from https://medium.com/@fawwazyusran/how-to-travis-ci-working-for-android-api-level-28-2fde7292813c
# needed special script to install android 28, build tools required by AGP 3.5.2

sudo: required
language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - sys-img-armeabi-v7a-google_apis-25

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'


before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "build-tools;28.0.3"
  - android create avd --force -n test -t android-25 --abi armeabi-v7a -c 100M
  - emulator -avd test -no-audio -no-window &
  #- echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test -k "sys-img-armeabi-v7a-google_apis-25" -c 100M
  #- $ANDROID_HOME/tools/emulator/emulator -avd test -no-audio -no-window &

install:
  #Run tasks in sequence so that Gradle doesn't run 'clean' in parallel with 'build'
  - ./gradlew clean
  - ./gradlew build --stacktrace
  - ./gradlew assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  # 82 is KEYCODE_MENU
  - adb shell input keyevent 82

script:
  - ./gradlew leakcanary-android-instrumentation:connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh || test true

env:
  global:
    - secure: "aWyY/jCiG/D7hHAprj0rG3xYafxRYjZM5oNqqbDfjUHvqPp7kS3SOhUd3SJMVuSR4kA5TuZQqMXHr10Jz05gcyowQE2XEnKmu1WkfNWz2TCNerF27O0TkuIgYyZxcOb1M4aMxDJPZgySLmsXQ+iuAly+RSFP/CcSP4WPU9YNsGCQZ1C8KfscCWxKR5n1GoOEboOIxE5BL11F4tYjINX45FcIdBJu5XKJhCqUUvjdwxrZ0BykSYpvgpZ0WwAcXUBHHoqcYnNYAhBi60G00OE2Ml1x5lXiC+5Kwpsi0mXoWMyDT7MIIqB+Fk6XzxEzE7+z2nYmssXpvfHDJe+N+osCxvgWL97dMwx6BLv0S2jaoNgtcBB/DpzJAGeQ3yFulK5npr7RpeKpFN60rj8vYaRK9EfAvTfiHOjA/gkfSLBYOk/hOmE6o363nAKqUss+5FMS9c2vgIatbJiYHWScqlMRPxS3IjLp9Y84jB8JN/T8Mexxsw07OmEtaAU5+di/Nv2ok1MIx25NA0XYsMKXReCkicYoXQcSBIj5fTUI6bD09OLS4hs1EacX0hIfF89TJKs6azu0VLJHWKoW2Uo+qqgVMQPXRkNAzCcrJGeUWep8O/DsoNlT40NZCXP5wJN/aWFK0Rrl5n1zM8VVWBPk/0CAS0VUDZZSnqGXo2vZV6+bYEk="
    - secure: "gdFVL5AOp5DhnaC2vJ5EYglenG3vOcJuMLQrnQsKzt+p2jb9jdu8Lbx3kr8UdKOXOPPQVwg1U8BILe8RPmkaURYgZLE9nPthEcEVfULRPbj7EDHxOQ0/3uWRbkq+GyxDtX4+tdnDQhEijW+hSIQdWHgUAwvvvxrKLVS37lYaj55VVtITljgsd07YYKMrFNFfH/tgDJdZClaiuXdLfrWzVEZKGHBJfyzGOjLmUSbZzXL/ut32mIqbVsxeDvXXxlBluS68UkG3wI5/gp1jAxBIc+NK+CoZMMb5ww6V1P+iZhA176YXm8WDiUHpEx6cH//rtnIJ+1IywBCG+S60JeVpUEu8N9NK/eVd2en5OSef9xqBYfCYHRKvI/S/DiR9CCbim7rnlVgHMrY580Nv/bnJ5E9Q/sQSD9pzKp0P452qU36FXJ+c519inc1+F5fEUApft0UzAVQFT9sY7qGV0d6x6D3BDyXGE4KMYWx4ydkSSCAI2bsvl/8dLUybU1kKBDivY71VU/bGtJ33LobySiSJA/03vTKHEsBuMowu13pnj7c5tp7QFFv3lRO1XXqT4NS39SySDQUT7UbZofsqHTyqMpiL72q1rII6af+XNskmILuwU/oRwR8+IN9LBE9Nz0uL3zOzv8uhzTZT2rUGEhDm+B51UMvK0ZEJDlpvA9Y2GTQ="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
